name: Run Tests
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm run install

      - name: Compile TypeScript
        run: npm run ts

      - name: Run tests
        run: npm run test
